config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
#  hello/urls.py

from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path('home', views.home_page_view, name='home'),
    path('poema_1', views.poema_1_view, name='poema_1'),
    path('poema_2', views.poema_2_view, name='poema_2'),
    path('poema_3', views.poema_3_view, name='poema_3')
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
#  hello/views.py

from django.shortcuts import render

def home_page_view(request):
	return render(request, 'website/layout.html')

def poema_1_view(request):
	return render(request, 'website/poema_1.html')

def poema_2_view(request):
	return render(request, 'website/poema_2.html')

def poema_3_view(request):
	return render(request, 'website/poema_3.html')

website/templates/website/layout.html
<!-- layout.html -->
{% load static %}
<link rel="stylesheet" href="{% static 'website/css/base.css' %}">
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
    		<title>Website</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	</head>
	<body>
	    <header class="jumbotron text-center">
            <h1></h1>
            <p></p>
            <nav>
                <a href="{% url 'website:poema_1' %}" class="btn btn-info">Poema 1</a>
                <a href="{% url 'website:poema_2' %}" class="btn btn-info">Poema 2</a>
                <a href="{% url 'website:poema_3' %}" class="btn btn-info">Poema 3</a>
            </nav>
        </header>
        <article class='center'>
            <main class="col-sm-6"> 
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-sm-6">
                {% load static %}
                <img src="{% static 'website/images/image.jpg' %}" width="200" height="200" class="center">
            </aside>
        </article>
        <footer>Texto simples de rodapé</footer>
	</body>
</html>

website/templates/website/poema_1.html
<!-- home.html -->

{% extends 'website/layout.html' %}

{% block main %}
    <h3>Poema 1</h3>
    <p>It was in the dark that the old moon shone &ndash; By day it hid.</p>

    <p>Snuck behind the trees in its still, slow journey, I wondered how the world turned &#8230; You could sharpen a knife on the gathering frost, Take home pocketfuls of stars for sweets, Stretch your ears to the wild shores in the silence.</p>
    
    <p>It was just a moment, too deep to understand: All I had was the moon, Making its slow journey.</p>
{% endblock %}

website/templates/website/poema_2.html
<!-- home.html -->

{% extends 'website/layout.html' %}

{% block main %}
    <h3>Poema 2</h3>
    <p>The sea stirs silent in a ripple On meddled shore, still dream hung, sun worn, Ships outdone by a shadowed pall As they sit like giant ghosts on the horizon.</p>

    <p>In the beckoning of our nets shrimps flick dismay invisibly, Fleet sand sparks leaving clouds of smoke To tell us that they&rsquo;ve gone</p>
{% endblock %}

website/templates/website/poema_3.html
<!-- home.html -->

{% extends 'website/layout.html' %}

{% block main %}
    <h3>Poema 3</h3>
    <p>I can&rsquo;t help myself with these poems, If poems are what they are &ndash; A few words that become a torrent and then subside, Well up again, Captured before they ebb away for all eternity: And in that capture I find some primitive release, A longing absolved, A pent-up problem solved.</p>
{% endblock %}